- name: Create Syncthing directory
  file:
    path: "{{ ansible_env.HOME }}/.syncthing"
    state: directory

- name: Download Syncthing
  unarchive:
    src: https://github.com/syncthing/syncthing/releases/download/v1.1.0/syncthing-linux-amd64-v1.1.0.tar.gz
    dest: "{{ ansible_env.HOME }}/.syncthing"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: Create systemd directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
  notify:
    - Restart Syncthing

- name: Set systemd service
  template:
    src: syncthing.service.j2
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/syncthing.service"
  notify:
    - Restart Syncthing

- name: Enable Syncthing
  systemd:
    daemon_reload: yes
    name: syncthing
    enabled: yes
    state: started
    user: yes
