- name: Create Syncthing directory
  file:
    path: "{{ ansible_env.HOME }}/.syncthing"
    state: directory

- name: Download Syncthing
  unarchive:
    src: https://github.com/syncthing/syncthing/releases/download/v1.2.2/syncthing-linux-amd64-v1.2.2.tar.gz
    dest: "{{ ansible_env.HOME }}/.syncthing"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  notify:
    - Restart Syncthing

- name: Create systemd directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
  notify:
    - Restart Syncthing

- name: Set systemd service
  template:
    src: syncthing.service.j2
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/syncthing.service"
  notify:
    - Restart Syncthing

- name: Enable Syncthing
  systemd:
    daemon_reload: yes
    name: syncthing
    enabled: yes
    state: started
    scope: user

- name: Wait for Syncthing to start
  wait_for:
    path: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"

- name: Set Syncthing GUI address
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/gui/address
    value: 127.0.0.1:8384
  notify:
    - Restart Syncthing

- name: Set Syncthing listen address
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/listenAddress
    value: tcp://127.0.0.1:22000
  notify:
    - Restart Syncthing

- name: Disable Syncthing global announce
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/globalAnnounceEnabled
    value: "false"
  notify:
    - Restart Syncthing

- name: Disable Syncthing local announce
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/localAnnounceEnabled
    value: "false"
  notify:
    - Restart Syncthing

- name: Disable Syncthing relays
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/relaysEnabled
    value: "false"
  notify:
    - Restart Syncthing

- name: Disable Syncthing start browser
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/startBrowser
    value: "false"
  notify:
    - Restart Syncthing

- name: Enable Syncthing nat traversal
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/natEnabled
    value: "true"
  notify:
    - Restart Syncthing

- name: Disable Syncthing auto upgrade
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/autoUpgradeIntervalH
    value: "0"
  notify:
    - Restart Syncthing

- name: Set Syncthing min disk free
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/minHomeDiskFree
    value: "5"
  notify:
    - Restart Syncthing

- name: Set Syncthing min disk free unit
  xml:
    file: "{{ ansible_env.HOME }}/.config/syncthing/config.xml"
    xpath: /configuration/options/minHomeDiskFree
    attribute: unit
    value: "%"
  notify:
    - Restart Syncthing
